# FDA Safety and Adverse Events
mcp_servers:
  tooluniverse_fda_safety:
    command: ["python", "-m", "biomni.tool.tooluniverse_mcp"]
    enabled: true
    tools:
      - biomni_name: FDA_get_drug_name_by_adverse_reaction
        description: "Get Drug Name By Adverse Reaction"
        parameters:
          adverse_reaction: {type: str, required: true, description: "Adverse Reaction"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_adverse_reactions_by_drug_name
        description: "Get Adverse Reactions By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_alarm
        description: "Get Drug Names By Alarm"
        parameters:
          alarm_type: {type: str, required: true, description: "Alarm Type"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_alarms_by_drug_name
        description: "Get Alarms By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_boxed_warning
        description: "Get Drug Names By Boxed Warning"
        parameters:
          warning_text: {type: str, required: true, description: "Warning Text"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_boxed_warning_info_by_drug_name
        description: "Get Boxed Warning Info By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_name_by_environmental_warning
        description: "Get Drug Name By Environmental Warning"
        parameters:
          environmental_warning: {type: str, required: true, description: "Environmental Warning"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_environmental_warning_by_drug_name
        description: "Get Environmental Warning By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_food_safety_warnings
        description: "Get Drug Names By Food Safety Warnings"
        parameters:
          field_info: {type: str, required: true, description: "Field Info"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_general_precautions
        description: "Get Drug Names By General Precautions"
        parameters:
          precaution_info: {type: str, required: true, description: "Precaution Info"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_general_precautions_by_drug_name
        description: "Get General Precautions By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_child_safety_info
        description: "Get Drug Names By Child Safety Info"
        parameters:
          child_safety_info: {type: str, required: true, description: "Child Safety Info"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_child_safety_info_by_drug_name
        description: "Get Child Safety Info By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_name_by_other_safety_info
        description: "Get Drug Name By Other Safety Info"
        parameters:
          safety_info: {type: str, required: true, description: "Safety Info"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_other_safety_info_by_drug_name
        description: "Get Other Safety Info By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_name_by_precautions
        description: "Get Drug Name By Precautions"
        parameters:
          precautions: {type: str, required: true, description: "Precautions"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_precautions_by_drug_name
        description: "Get Precautions By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_residue_warning
        description: "Get Drug Names By Residue Warning"
        parameters:
          residue_warning: {type: str, required: true, description: "Residue Warning"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_residue_warning_by_drug_name
        description: "Get Residue Warning By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_risk
        description: "Get Drug Names By Risk"
        parameters:
          risk_info: {type: str, required: true, description: "Risk Info"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_risk_info_by_drug_name
        description: "Get Risk Info By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_safety_summary
        description: "Get Drug Names By Safety Summary"
        parameters:
          summary_text: {type: str, required: true, description: "Summary Text"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_safety_summary_by_drug_name
        description: "Get Safety Summary By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_user_safety_warning_by_drug_names
        description: "Get User Safety Warning By Drug Names"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_user_safety_warning
        description: "Get Drug Names By User Safety Warning"
        parameters:
          safety_warning: {type: str, required: true, description: "Safety Warning"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_name_by_warnings
        description: "Get Drug Name By Warnings"
        parameters:
          warning_text: {type: str, required: true, description: "Warning Text"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_warnings_by_drug_name
        description: "Get Warnings By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_warnings_and_cautions_by_drug_name
        description: "Get Warnings And Cautions By Drug Name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
      - biomni_name: FDA_get_drug_names_by_warnings_and_cautions
        description: "Get Drug Names By Warnings And Cautions"
        parameters:
          warnings_and_cautions_info: {type: str, required: true, description: "Warnings And Cautions Info"}
          indication: {type: str, required: true, description: "Indication"}
          limit: {type: int, required: true, description: "Maximum number of results to return"}
          skip: {type: int, required: true, description: "Number of results to skip"}
