mcp_servers:
  pubmed:
    command: ["python", "-m", "biomni.tool.mcp_tools.pubmed_mcp"]
    enabled: true
    tools:
      - biomni_name: search_pubmed
        description: "Search PubMed"
        parameters:
          query:        {type: str, required: true,  description: "PubMed search term"}
          max_results:  {type: int, required: false, default: 10, description: "Maximum number of hits"}
      - biomni_name: get_article_abstract
        description: "Fetch PubMed abstract"
        parameters:
          pmid: {type: str, required: true, description: "PubMed ID"}

  tooluniverse:
    command: ["python", "-m", "biomni.tool.mcp_tools.tooluniverse_mcp"]
    enabled: true
    tools:
      - biomni_name: FDA_get_active_ingredient_info_by_drug_name
        description: "Get FDA active ingredient information by drug name"
        parameters:
          drug_name: {type: str, required: true, description: "Name of the drug to search for"}
          limit:     {type: int, required: true, description: "Maximum number of results to return"}
          skip:      {type: int, required: true, description: "Number of results to skip"}
